# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9bf8edb731368fa0e7af16571ab02d1367ad8c4c2f282c2cae2bb41f1a5cd98d6265ffefe44d40343e4845d423d3e54af396e887c29f0aa062987633681a300

test:
  secret_key_base: de75f547bdd21594d6177cb55f3d223b53acfa4902755f515f457fc71959e5ccedf92e0ac32cbe47393c23ca9b7aecf46929cf0986b553a88599a60b8547a916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
